routes/web.php
<?php


use App\User;

Auth::routes();
Route::get('/', 'HomeController@index')->name('dashboard')->middleware('auth');

// user
Route::get('/user','UserController@index')->middleware('auth');
Route::get('/user/add',['as'=>'user.add','uses'=>'UserController@create'])->middleware('auth');
Route::post('/user/create',['as'=>'user.create','uses'=>'UserController@store'])->middleware('auth');
Route::get('/user/delete/{id}',['as'=>'user.delete','uses'=>'UserController@destroy'])->middleware('auth');
Route::get('/user/edit/{id}',['as'=>'user.edit','uses'=>'UserController@edit'])->middleware('auth');
Route::put('/user/update/{id}',['as'=>'user.update','uses'=>'UserController@update'])->middleware('auth');
//end user

// Expense Type
Route::get('/expense-type/create' ,'ExpenseTypeController@create')->name('createExpenseType')->middleware('auth');
Route::get('/expense-type' ,'ExpenseTypeController@index')->middleware('auth');

// Resourceful Route
Route::resource('employee' ,'EmployeeController')->middleware('auth');
Route::get('salary' ,'EmployeeController@salary')->name('check-salary')->middleware('auth');
Route::post('check-salary' ,'EmployeeController@CheckSalary')->name('post-salary')->middleware('auth');
Route::get('tada' ,'EmployeeController@tada')->name('check-tada')->middleware('auth');
Route::post('tada' ,'EmployeeController@tada_post')->name('check-tada-post')->middleware('auth');
Route::post('pay-tada' ,'TadaController@PayTada')->name('pay-tada')->middleware('auth');
Route::resource('employee-expense' ,'EmployeeExpenseController')->middleware('auth');
Route::resource('attendance' ,'AttendanceController')->middleware('auth');
Route::resource('off-day' ,'OffDayController')->middleware('auth');
Route::resource('company-expense' ,'CompanyExpenseController')->middleware('auth');
Route::post('com_ex' ,'CompanyExpenseController@list')->name('com_ex')->middleware('auth');
Route::post('office_ex' ,'OfficeExpenseController@list')->name('office_ex')->middleware('auth');

Route::resource('office-expense' ,'OfficeExpenseController')->middleware('auth');
Route::get('attendance-edit' ,'AttendanceController@editAttendance')->middleware('auth');
Route::post('attendance-update' ,'AttendanceController@updateAttendance')->middleware('auth');

// Routes for Ajax / Axios Call
Route::get('all_employee','EmployeeController@AllEmployee')->middleware('auth');
Route::get('all_employee_expense','EmployeeExpenseController@AllEmployeeExpense')->middleware('auth');
Route::get('all_attendance','AttendanceController@AllAttendance')->middleware('auth');
Route::get('all_off','AttendanceController@AllOff')->middleware('auth');
Route::get('all_off_employee','EmployeeController@all_off_employee')->middleware('auth');
Route::post('all_employee/{id}/{m_id}','EmployeeExpenseController@FindEmployee')->middleware('auth');
Route::post('save_expense_e/{id}','EmployeeExpenseController@SaveEx')->middleware('auth');
Route::delete('delete_expense/{id}','EmployeeExpenseController@DeleteEx')->middleware('auth');
Route::post('add_leave','AttendanceController@addLeave')->middleware('auth');
Route::get('get_leave','AttendanceController@getLeave')->middleware('auth');
Route::post('create-expense-type','ExpenseTypeController@store')->middleware('auth');
Route::post('generate-expense-type','ExpenseTypeController@show')->middleware('auth');

// Export to excel
Route::get('export','ExpenseTypeController@export')->middleware('auth');
Route::get('salary-export','EmployeeController@exportSalary')->middleware('auth');
Route::get('attendance-export','AttendanceController@exportAttendance')->middleware('auth');
Route::get('employee-export','EmployeeController@exportEmployee')->middleware('auth');


//Products Route
Route::resource('product', 'ProductController')->middleware('auth');

//Sales Route
Route::resource('sale', 'SalesController')->middleware('auth');
Route::post('/import', 'SalesController@import')->middleware('auth');
Route::get('/sales-report', 'SalesController@sales_report')->middleware('auth');
Route::post('/generate-sales-report', 'SalesController@sales_report')->middleware('auth');
Route::get('/sales_details/{id}', 'SalesController@sales_details')->name('sales_details')->middleware('auth');

//Stocks Route
Route::get('/stocks-list', 'StockController@index')->middleware('auth');
Route::get('/add-stocks', 'StockController@create')->middleware('auth');
Route::post('/import-stocks', 'StockController@import')->middleware('auth');

//Retail Market Route
Route::get('/retail-market', 'RetailMarketController@index')->middleware('auth');
Route::post('/retail-market-details', 'RetailMarketController@retail_market')->middleware('auth');

// Michallencious
Route::get('add-designation', 'EmployeeController@addDesignation')->name('add-designation')->middleware('auth');
Route::post('create-designation', 'EmployeeController@createDesignation')->name('create-designation')->middleware('auth');
Route::get('tada-export' ,'TadaController@export')->name('tada-export')->middleware('auth');


//ROI
Route::get('/roi', 'RoiController@index')->middleware('auth');
Route::post('/roi-details', 'RoiController@details')->middleware('auth');
Route::get('/pending_claim', 'RoiController@pending_claim')->middleware('auth');
Route::get('/investments', 'InvestmentController@index')->middleware('auth');
Route::get('/add-investment', 'InvestmentController@create')->middleware('auth');
Route::post('/store-investment', 'InvestmentController@store')->middleware('auth');
Route::get('/add-investment-details', 'InvestmentController@create_details')->middleware('auth');
Route::post('/store-investment-details', 'InvestmentController@store_details')->middleware('auth');

//other info
Route::get('/other-info', 'OtherInfoController@index')->middleware('auth');
Route::post('/store-other-info', 'OtherInfoController@store')->middleware('auth');

//shop
Route::resource('shop', 'ShopController')->middleware('auth');

//cheque
Route::get('cheque', 'ChequeController@index')->middleware('auth');
Route::get('cheque_pass/{id}', 'ChequeController@cheque_pass')->middleware('auth');
Route::get('cheque_bounce/{id}', 'ChequeController@cheque_bounce')->middleware('auth');

//register
Route::get('register', 'RegisterController@index');

//Provident Fund 
Route::get('/provident_fund_list' ,'EmployeeController@ProvidentList')->name('provident-fund-list');
Route::get('/provident_fund_pay/{employee}' ,'EmployeeController@ProvidentPay')->name('provident-fund-pay');
Route::post('/provident_fund_post' ,'EmployeeController@ProvidentPost')->name('provident-fund-post');

//Sales Values
Route::get('/sales-edit/{id}', 'Sale_valuesController@edit');
Route::put('/sales-update/{id}', 'Sale_valuesController@update');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Cash_flow;
use App\Cheque;
use App\CompanyExpense;
use App\Due;
use App\DueRealize;
use App\Employee;
use App\Employee_exchange;
use App\Imports\SalesImport;
use App\Sale;
use App\Sale_value;
use App\Shop;
use App\Stock;
use Carbon\Carbon;
use DB;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class SalesController extends Controller
{	
    public function __construct()
    {
        $this->middleware('auth');
    }
	public function index()
    {
        $sales = Sale_value::leftJoin('employees', function($join) {
                      $join->on('sale_values.employee_id', '=', 'employees.id');
                    })
                ->select('sale_values.*', 'employees.name', 'employees.id as employee_id')
                ->orderBy('sale_values.id', 'DESC')
                ->get();
		return view('sales.index', compact('sales'));
	}

	public function create()
    {
		$employee_data = Employee::all();
        $shops = Shop::all();
		return view('sales.add', compact("employee_data", "shops"));
	}

	//imports excel 
    public function import(Request $request)
    {      
        $array = (new SalesImport)->toArray(request()->file('excel_file'));
        //insert sales list
        for ($i = 12; $i < count($array[0]); $i++) 
        {
        	if ($array[0][$i][1] !== "Total") 
            {   
        		$sale = new Sale();
        		$sale->employee_id = $request->employee;
        		$sale->sku_code = $array[0][$i][1];
        		$sale->sku = $array[0][$i][2];
        		$sale->pack_size = $array[0][$i][5];
        		$sale->ctn_sale = $array[0][$i][9];
        		$sale->unit_sale = $array[0][$i][11];
        		$sale->ctn_free = $array[0][$i][14];
        		$sale->unit_free = $array[0][$i][16];
        		$sale->ctn_return = $array[0][$i][17];
        		$sale->unit_return = $array[0][$i][18];
        		$sale->sales_value = $array[0][$i][23];
                $sale->created_at = $request->date;
        		$sale->save();

                //decrement from stock
                $total_sale_ctn = $array[0][$i][9] + $array[0][$i][14];
                $total_sale_unit = $array[0][$i][11] + $array[0][$i][16];

                $stocks = Stock::where('sku_code', $array[0][$i][1])->count();
                if ($stocks > 0) 
                {
                    Stock::where('sku_code', $array[0][$i][1])->decrement('available_ctn', $total_sale_ctn);
                    Stock::where('sku_code', $array[0][$i][1])->decrement('available_pcs', $total_sale_unit);
                }
        	}
        	else
            {
        		break;
        	}  	
        } //end for

        //insert sales values
        for ($i = 12; $i < count($array[0]); $i++) 
        {

        	if ($array[0][$i][1] == "Free Value                      :")
            {

        		$credit_given = (float) filter_var( $array[0][$i+17][4], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION );
        		$prev_credit_collected = (float) filter_var( $array[0][$i+21][4], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION );
        		$expenses = (float) filter_var( $array[0][$i+25][4], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION );
        		$store_discount = (float) filter_var( $array[0][$i+33][4], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION );
        		$free = $array[0][$i+1][4];
        		$discount = $array[0][$i+5][4];
        		$promo_discount = $array[0][$i+9][4];
        		$market_return = $array[0][$i+29][4];
        		$cash_to_be_deposite = $array[0][$i+37][4];
                $cash_deposite = $request->cash_deposite;

        		$cash_issue = ($free + $discount + $promo_discount + $credit_given +  $prev_credit_collected + $expenses + $market_return + $store_discount + $cash_to_be_deposite);

        		$sale_value = new Sale_value();
        		$sale_value->employee_id = $request->employee;
        		$sale_value->cash_issue = $cash_issue;
        		$sale_value->free = $free;
        		$sale_value->discount = $discount;
        		$sale_value->promo_discount = $promo_discount;
        		$sale_value->credit_given = $credit_given;
        		$sale_value->prev_credit_collected = $prev_credit_collected;
        		$sale_value->expenses = $expenses;
        		$sale_value->market_return = $market_return;
        		$sale_value->store_discount = $store_discount;
                $sale_value->cash_to_be_deposite = $cash_to_be_deposite;
        		$sale_value->cash_deposited = $cash_deposite;
                $sale_value->created_at = $request->date;
        		$sale_value->save();
        	}
       	}//end for


        //shoppers
        $total_due = $total_due_realize = $total_cheque_amount = 0;

        //due
        $due_shop = $request->shop_due;
        $due_amount = $request->due_amount;

        $sales = Sale_value::select('id')
                           ->where('cash_to_be_deposite', $cash_to_be_deposite)
                           ->where('cash_deposited', $cash_deposite)
                           ->where('employee_id', $request->employee)
                           ->where('cash_issue', $cash_issue)
                           ->first();

        if ($request->has('shop_due') && $request->has('due_amount')) 
        {   
            for ($i=0; $i < count($due_amount); $i++) 
            { 
                $dues = new Due;
                $dues->shop_id = $due_shop[$i];
                $dues->sales_id = $sales->id;
                $dues->amount = $due_amount[$i];
                $dues->save();
                $total_due += $due_amount[$i];
            }
        }

        //cheque payment
        $shop_cheque_pay = $request->shop_cheque_pay;
        $cheque_amount = $request->cheque_amount;
        $cheque_number = $request->cheque_number;
        $deposite_date = $request->deposite_date;

        if ($request->has('shop_cheque_pay') && $request->has('cheque_amount') && $request->has('cheque_number') && $request->has('deposite_date')) 
        {   
            for ($i=0; $i < count($cheque_amount); $i++) 
            { 
                $cheques = new Cheque;
                $cheques->shop_id = $shop_cheque_pay[$i];
                $cheques->sales_id = $sales->id;
                $cheques->number = $cheque_number[$i];
                $cheques->amount = $cheque_amount[$i];
                $cheques->received_date = $request->date;
                $cheques->deposite_date = $deposite_date[$i];
                $cheques->type = 'payment';
                $cheques->save();
                $total_cheque_amount += $cheque_amount[$i];
            }
        }

        //due realize
        $shop_due_realize = $request->shop_due_realize;
        $due_realize_amount = $request->amount;
        $payment_type = $request->payment_type;
        $due_realize_cheque_number = $request->due_realize_cheque_number;
        $deposite_date_due_realize = $request->deposite_date_due_realize;

        if ($request->has('shop_due_realize') && $request->has('amount') && $request->has('payment_type') && $request->has('due_realize_cheque_number') && $request->has('deposite_date_due_realize')) 
        {   
            for ($i=0; $i < count($due_realize_amount); $i++) 
            { 
                $due_realizes = new DueRealize;
                $due_realizes->shop_id = $shop_due_realize[$i];
                $due_realizes->sales_id = $sales->id;
                $due_realizes->amount = $due_realize_amount[$i];
                $due_realizes->payment_type = $payment_type[$i];

                if ($payment_type[$i] == 'cheque') {
                    $cheques = new Cheque;
                    $cheques->shop_id = $shop_due_realize[$i];
                    $cheques->sales_id = $sales->id;
                    $cheques->number = $due_realize_cheque_number[$i];
                    $cheques->amount = $due_realize_amount[$i];
                    $cheques->received_date = $request->date;
                    $cheques->deposite_date = $deposite_date_due_realize[$i];
                    $cheques->type = 'due_realize';
                    $cheques->save();
                }else {
                    $total_due_realize += $due_realize_amount[$i];
                }

                $cheque_no = Cheque::where('number', $due_realize_cheque_number[$i])->first();

                (!empty($cheque_no)) ? $due_realizes->cheque_id = $cheque_no->id : '';
                $due_realizes->save();
                
            }
        }

        //final cash to be deposite
        $final_cash_to_be_deposite = $cash_to_be_deposite - $total_due - $total_cheque_amount + $total_due_realize;
        

        if ($cash_deposite > $final_cash_to_be_deposite) 
        {
            $cash_excess =  $cash_deposite - $final_cash_to_be_deposite;
            Sale_value::find($sales->id)->update([
                        'cash_to_be_deposite' => $cash_excess,
                        'cash_excess' => $cash_excess,
                    ]);
            Cash_flow::where('employee_id', $request->employee)->increment('cash_excess', round($cash_excess));
        }
        else
        {
            $cash_short = $final_cash_to_be_deposite - $cash_deposite;
            Sale_value::find($sales->id)->update([
                        'cash_to_be_deposite' => $final_cash_to_be_deposite,
                        'cash_short' => $cash_short,
                    ]);
            Cash_flow::where('employee_id', $request->employee)->increment('cash_short', round($cash_short));
        }
		
        return back()->with('success', 'Sales Excel Sheet is Successfully Imported');
    }

    public function sales_details(sale_value $sale_value, $id)
    {   
        $sales_value_details = Sale_value::where('id', $id)
                                    ->where('employee_id', request()->employee)
                                    ->whereDate('created_at', request()->date)
                                    ->first();

resources/views/sales/add.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('success'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('success') }}
        </div>
@endif

<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<div class="box-header with-border">
						<legend class="box-title" style="text-align: center; font-weight: bold;">Add New Sales</legend>
					</div>
				</div>
				<div class="col-md-3"></div>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ url('/import') }}">
				@csrf

				<div class="row">
					<div class="col-md-3"></div>
					<div class="form-group">
						<div class="col-md-2">
							<label for="employee">Select Employee :</label>
						</div>
						<div class="col-md-4">	
							
							<select name="employee" class="form-control" required="">
								<option value="">Select</option>
								@foreach($employee_data as $employee)
									<option value="{{$employee->id}}">{{ $employee->name }}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="col-md-3"></div>
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="cash_deposite">Cash Deposite/ Given :</label>
						</div>
						<div class="col-md-4">
							<input type="number" name="cash_deposite" value="{{ old('cash_deposite') }}" class="form-control" placeholder="Enter Amount" required="">
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="date">Date :</label>
						</div>
						<div class="col-md-4">
							<input type="date" name="date" class="form-control" required="" value="{{ old('date', date('Y-m-d')) }}">
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="excel_file">Select Sales Excel File :</label>
						</div>
						<div class="col-md-4">
							<input type="file" name="excel_file" class="form-control" required="">
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>
				
				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="due">Add Due :</label>
						</div>
						<div class="col-md-4">
							<button type="button" id="due" class="btn btn-info btn-sm">Add</button>
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-5"></div>
						<div class="col-md-4 shop_due">
							
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="due">Cheque Payment :</label>
						</div>
						<div class="col-md-4">
							<button type="button" id="cheque" class="btn btn-info btn-sm">Add</button>
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-5"></div>
						<div class="col-md-4 cheque_payment">
							
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-2">
							<label for="due">Due Realize :</label>
						</div>
						<div class="col-md-4">
							<button type="button" id="due_realize" class="btn btn-info btn-sm">Add</button>
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-5"></div>
						<div class="col-md-4 due_realize">
							
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<!-- /.box-body -->
				<div class="box-footer">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<button type="submit" class="btn btn-primary col-sm-12">Submit <i class="fa fa-check"></i></button>
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>









<script type="text/javascript">
	  
	  //due
	  $(document).ready(function(){
	      $("#due").click(function(){
	          $(".shop_due").append(`
	    <div><select name="shop_due[]" class="form-control">
	    	<option value="">--- select ---</option>
	    	<?php
	    	foreach($shops as $shop)
	    	{ ?>
	    		<option value="<?= $shop->id; ?>"><?= $shop->shop_name; ?></option>
	    	<?php } ?>
	    	
	    </select>
		<input type="number" name="due_amount[]" class="form-control" style="margin-top:5px;" placeholder="Enter Due Amount" required>
		<a href="#" class="remove">Remove</a></<div>
	    	
	    </div>
	    <br>
	  `); 
	      });
	      $(document).on("click", "a.remove" , function() {
	          $(this).parent('div').remove();
	      });
	  });	

	  	//cheque payment
	    $(document).ready(function(){
	        $("#cheque").click(function(){
	            $(".cheque_payment").append(`
	      <div><select name="shop_cheque_pay[]" class="form-control">
	      	<option value="">--- select ---</option>
	      	<?php
	      	foreach($shops as $shop)
	      	{ ?>
	      		<option value="<?= $shop->id; ?>"><?= $shop->shop_name; ?></option>
	      	<?php } ?>
	      	
	      </select>
	  	<input type="number" name="cheque_amount[]" class="form-control" style="margin-top:5px;" placeholder="Enter Amount" required>
	  	<input type="number" name="cheque_number[]" class="form-control" style="margin-top:5px;" placeholder="Enter Cheque Number" required>
	  	<input type="date" name="deposite_date[]" class="form-control" value="<?php echo date('Y-m-d');?>" style="margin-top:5px;">

	  	<a href="#" class="remove2">Remove</a></<div>
	      	
	      </div>
	      <br>
	    `); 
	        });
	        $(document).on("click", "a.remove2" , function() {
	            $(this).parent('div').remove();
	        });
	    });

	      //due realize  
	      $(document).ready(function(){
	          $("#due_realize").click(function(){
	              $(".due_realize").append(`
	        <div><select name="shop_due_realize[]" class="form-control">
	        	<option value="">--- select ---</option>
	        	<?php
	        	foreach($shops as $shop)
	        	{ ?>
	        		<option value="<?= $shop->id; ?>"><?= $shop->shop_name; ?></option>
	        	<?php } ?>
	        	
	        </select>
	    	<input type="number" name="amount[]" class="form-control" style="margin-top:5px;" placeholder="Enter Amount" required>
	    	<select name="payment_type[]" class="form-control" style="margin-top:5px;">
	    		        	<option value="">--- select ---</option>
	    		    		<option value="cash">Cash</option>
	    		    		<option value="cheque">Cheque</option>
	    		        </select>
	    	<input type="number" name="due_realize_cheque_number[]" class="form-control" style="margin-top:5px;" placeholder="Cheque Number(if payment method is cheque)">
	    	<input type="date" name="deposite_date_due_realize[]" class="form-control" value="<?php echo date('Y-m-d');?>" style="margin-top:5px;">
	    	<a href="#" class="remove3">Remove</a></<div>
	        </div><br>
	      `); 
	          });
	          $(document).on("click", "a.remove3" , function() {
	              $(this).parent('div').remove();
	          });
	      });
</script>

@endsection

resources/views/sales/edit.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('success'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('success') }}
        </div>
@endif

<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<div class="box-header with-border">
						<legend class="box-title" style="text-align: center; font-weight: bold;">Edit Sales</legend>
					</div>
				</div>
				<div class="col-md-3"></div>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" action="{{ url('/sales-update/'.$sales_info->id) }}">
				@csrf
				@method('PUT')
				<div class="box-body">
					<div class="row">
						<div class="col-md-1"></div>
						<div class="col-md-4">
							<label for="cash_deposite" style="float: right;">Edit Cash Deposite/ Given :</label>
						</div>
						<div class="col-md-4">
							<input type="number" name="cash_deposite" value="{{ $sales_info->cash_deposited }}" class="form-control" required="">
						</div>
						<div class="col-md-3"></div>
					</div>		
				</div>

				<!-- /.box-body -->
				<div class="box-footer">
					<div class="row">
						<div class="col-md-5"></div>
						<div class="col-md-4">
							<button type="submit" class="btn btn-primary col-sm-12">Submit <i class="fa fa-check"></i></button>
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/sales/index.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">All Sales</h3>
        <a href="{{ route('sale.create') }}" class="text-right btn btn-success"><i class="fa fa-users fa-fw"></i> Add Sale</a>
    </div>
</div>


<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example1_info" style="text-align: center;">
                    <thead>
                        <tr>
                            <th style="text-align: center;">Sale ID</th>
                            <th style="text-align: center;">Salesman</th>
                            <th style="text-align: center;">Sale Date</th>
                            <th style="text-align: center;">View Sales Details</th>
                            <th style="text-align: center;">Edit</th>
                        </tr>
                    </thead>
                            
                    <tbody>
                    	@foreach($sales as $sale)
	                    	<tr>
	                    		<td>{{ $sale->id }}</td>
	                    		<td>{{ $sale->name }}</td>
	                    		<td>{{ Carbon\Carbon::parse($sale->created_at->toDateString())->format('d-M-Y') }}</td>
	                    		<td>
                                    <form action="{{ url('/sales_details/'.$sale->id) }}" method="get" target="new">
                                        <input type="hidden" name="date" value="{{ Carbon\Carbon::parse($sale->created_at->toDateString())->format('Y-m-d') }}">
                                        <input type="hidden" name="employee" value="{{ $sale->employee_id }}">
                                        <button type="submit" class="btn btn-info">Details</button>
                                    </form>
	                    		</td>
                                <td>
                                    <a href="{{ url('/sales-edit/'.$sale->id) }}" title="Edit" class="btn btn-primary" target="_blank"><i class="fa fa-edit"></i></a>
                                </td>
	                    	</tr>            
	                    @endforeach
	                        
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>




@endsection