routes/web.php
<?php


use App\User;

Auth::routes();
Route::get('/', 'HomeController@index')->name('dashboard')->middleware('auth');

// user
Route::get('/user','UserController@index')->middleware('auth');
Route::get('/user/add',['as'=>'user.add','uses'=>'UserController@create'])->middleware('auth');
Route::post('/user/create',['as'=>'user.create','uses'=>'UserController@store'])->middleware('auth');
Route::get('/user/delete/{id}',['as'=>'user.delete','uses'=>'UserController@destroy'])->middleware('auth');
Route::get('/user/edit/{id}',['as'=>'user.edit','uses'=>'UserController@edit'])->middleware('auth');
Route::put('/user/update/{id}',['as'=>'user.update','uses'=>'UserController@update'])->middleware('auth');
//end user

// Expense Type
Route::get('/expense-type/create' ,'ExpenseTypeController@create')->name('createExpenseType')->middleware('auth');
Route::get('/expense-type' ,'ExpenseTypeController@index')->middleware('auth');

// Resourceful Route
Route::resource('employee' ,'EmployeeController')->middleware('auth');
Route::get('salary' ,'EmployeeController@salary')->name('check-salary')->middleware('auth');
Route::post('check-salary' ,'EmployeeController@CheckSalary')->name('post-salary')->middleware('auth');
Route::get('tada' ,'EmployeeController@tada')->name('check-tada')->middleware('auth');
Route::post('tada' ,'EmployeeController@tada_post')->name('check-tada-post')->middleware('auth');
Route::post('pay-tada' ,'TadaController@PayTada')->name('pay-tada')->middleware('auth');
Route::resource('employee-expense' ,'EmployeeExpenseController')->middleware('auth');
Route::resource('attendance' ,'AttendanceController')->middleware('auth');
Route::resource('off-day' ,'OffDayController')->middleware('auth');
Route::resource('company-expense' ,'CompanyExpenseController')->middleware('auth');
Route::post('com_ex' ,'CompanyExpenseController@list')->name('com_ex')->middleware('auth');
Route::post('office_ex' ,'OfficeExpenseController@list')->name('office_ex')->middleware('auth');

Route::resource('office-expense' ,'OfficeExpenseController')->middleware('auth');
Route::get('attendance-edit' ,'AttendanceController@editAttendance')->middleware('auth');
Route::post('attendance-update' ,'AttendanceController@updateAttendance')->middleware('auth');

// Routes for Ajax / Axios Call
Route::get('all_employee','EmployeeController@AllEmployee')->middleware('auth');
Route::get('all_employee_expense','EmployeeExpenseController@AllEmployeeExpense')->middleware('auth');
Route::get('all_attendance','AttendanceController@AllAttendance')->middleware('auth');
Route::get('all_off','AttendanceController@AllOff')->middleware('auth');
Route::get('all_off_employee','EmployeeController@all_off_employee')->middleware('auth');
Route::post('all_employee/{id}/{m_id}','EmployeeExpenseController@FindEmployee')->middleware('auth');
Route::post('save_expense_e/{id}','EmployeeExpenseController@SaveEx')->middleware('auth');
Route::delete('delete_expense/{id}','EmployeeExpenseController@DeleteEx')->middleware('auth');
Route::post('add_leave','AttendanceController@addLeave')->middleware('auth');
Route::get('get_leave','AttendanceController@getLeave')->middleware('auth');
Route::post('create-expense-type','ExpenseTypeController@store')->middleware('auth');
Route::post('generate-expense-type','ExpenseTypeController@show')->middleware('auth');

// Export to excel
Route::get('export','ExpenseTypeController@export')->middleware('auth');
Route::get('salary-export','EmployeeController@exportSalary')->middleware('auth');
Route::get('attendance-export','AttendanceController@exportAttendance')->middleware('auth');
Route::get('employee-export','EmployeeController@exportEmployee')->middleware('auth');


//Products Route
Route::resource('product', 'ProductController')->middleware('auth');

//Sales Route
Route::resource('sale', 'SalesController')->middleware('auth');
Route::post('/import', 'SalesController@import')->middleware('auth');
Route::get('/sales-report', 'SalesController@sales_report')->middleware('auth');
Route::post('/generate-sales-report', 'SalesController@sales_report')->middleware('auth');
Route::get('/sales_details/{id}', 'SalesController@sales_details')->name('sales_details')->middleware('auth');

//Stocks Route
Route::get('/stocks-list', 'StockController@index')->middleware('auth');
Route::get('/add-stocks', 'StockController@create')->middleware('auth');
Route::post('/import-stocks', 'StockController@import')->middleware('auth');

//Retail Market Route
Route::get('/retail-market', 'RetailMarketController@index')->middleware('auth');
Route::post('/retail-market-details', 'RetailMarketController@retail_market')->middleware('auth');

// Michallencious
Route::get('add-designation', 'EmployeeController@addDesignation')->name('add-designation')->middleware('auth');
Route::post('create-designation', 'EmployeeController@createDesignation')->name('create-designation')->middleware('auth');
Route::get('tada-export' ,'TadaController@export')->name('tada-export')->middleware('auth');


//ROI
Route::get('/roi', 'RoiController@index')->middleware('auth');
Route::post('/roi-details', 'RoiController@details')->middleware('auth');
Route::get('/pending_claim', 'RoiController@pending_claim')->middleware('auth');
Route::get('/investments', 'InvestmentController@index')->middleware('auth');
Route::get('/add-investment', 'InvestmentController@create')->middleware('auth');
Route::post('/store-investment', 'InvestmentController@store')->middleware('auth');
Route::get('/add-investment-details', 'InvestmentController@create_details')->middleware('auth');
Route::post('/store-investment-details', 'InvestmentController@store_details')->middleware('auth');

//other info
Route::get('/other-info', 'OtherInfoController@index')->middleware('auth');
Route::post('/store-other-info', 'OtherInfoController@store')->middleware('auth');

//shop
Route::resource('shop', 'ShopController')->middleware('auth');

//cheque
Route::get('cheque', 'ChequeController@index')->middleware('auth');
Route::get('cheque_pass/{id}', 'ChequeController@cheque_pass')->middleware('auth');
Route::get('cheque_bounce/{id}', 'ChequeController@cheque_bounce')->middleware('auth');

//register
Route::get('register', 'RegisterController@index');

//Provident Fund 
Route::get('/provident_fund_list' ,'EmployeeController@ProvidentList')->name('provident-fund-list');
Route::get('/provident_fund_pay/{employee}' ,'EmployeeController@ProvidentPay')->name('provident-fund-pay');
Route::post('/provident_fund_post' ,'EmployeeController@ProvidentPost')->name('provident-fund-post');

//Sales Values
Route::get('/sales-edit/{id}', 'Sale_valuesController@edit');
Route::put('/sales-update/{id}', 'Sale_valuesController@update');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Attendance;

use App\ProvidentFund;
use App\CashFlow;
use App\Designation;
use App\Employee;
use App\EmployeeExpense;
use App\OffDay;
use App\Tada;
use Carbon\Carbon;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator; 

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function ProvidentList()
    {
        $data['employees'] = Employee::with('provident')->get();
        return view('provident_fund.list',$data);
    }
    
    public function ProvidentPay($employee)
    {
        $data['employee'] = Employee::find($employee)->first();
        return view('provident_fund.pay',$data);
    }
    public function ProvidentPost(Request $request)
    {
        $fund = ProvidentFund::create([
            'employee_id' => $request->id,
            'paid_amount' => $request->amount
            ]);
        if($fund){
            Session::flash('msg', 'Provident Fund paid!');
            return redirect()->route('provident-fund-list');    
        }
        
    }

    public function AllEmployee()
    {
        $employees = Employee::with('off_day')->get();
        return response()->json($employees);
    }

    
    public function all_off_employee()
    {
        // dd(Employee::with('off_today')->get());
        $employees = Employee::with('off_day')->get();
//         $employees = Employee::with("off_day")->whereHas("off_day",function($q){
//     $q->where('off_date', '=', Carbon::now()->format('l'));
// })->get();
        return response()->json($employees);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['employees'] = Employee::all();
        return view('employees.employee-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['designations'] = Designation::all();
        return view('employees.add',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all() ,[
            'name' => 'string|required|max:255',
            'email' => 'required|email|unique:employees',
            'phone' => 'required|regex:/(01)[0-9]{9}/|unique:employees',
            'gender' => 'required',
            'dob' => 'required|date',
            'present_addr' => 'required',
            'permanent_addr' => 'required',
            'department' => 'required',
            'designation' => 'required',
            'join_date' => 'required',
            'provident_fund' => 'required',
            'salary' => 'required',
            'tada' => 'required',
            'employee_type' => 'required',
            'photo' => 'sometimes|image',
            'father_name' => 'sometimes|string',
        ]);

        if ($validator->fails()) {
            $request->session()->flash('err', 'Please check the highlighted inputs!');
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public');
        }


        $employee = Employee::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'dob' => date('Y-m-d', strtotime($request->dob)),
            'present_addr' => $request->present_addr,
            'permanent_addr' => $request->permanent_addr,
            'department' => $request->department,
            'designation' => $request->designation,
            'join_date' => date('Y-m-d', strtotime($request->join_date)),
            'provident_fund' => $request->provident_fund,
            'salary' => $request->salary,
            'father_name' => $request->father_name,
            'tada' => $request->tada,
            'employee_type' => $request->employee_type,
            'photo' => $photo ?? null
        ]);

        $cash_flow_for_employee = new CashFlow;
        $cash_flow_for_employee->employee_id = $employee->id;
        $cash_flow_for_employee->cash_short = 0;
        $cash_flow_for_employee->cash_excess = 0;
        $cash_flow_for_employee->save();

        if ($employee) {
            $request->session()->flash('msg', 'Employee Created Successfully!');
            return redirect()->route('employee.index');
        } else{
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        $id = $employee;
        $data['employee'] = Employee::findOrFail($id)->first();
        return view('employees.profile',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $id = $employee;
        $data['designations'] = Designation::all();
        $employee = Employee::findOrFail($id)->first();
        if($employee){
            return view('employees.edit',$data)->with('employee' , $employee);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $id = $employee;
        $f_employee = Employee::findOrFail($id)->first();

        $validator = Validator::make($request->all() ,[
            'name' => 'string|required|max:255',
            'email' => 'required|email|unique:employees,email,'.$f_employee->id,
            'phone' => 'required|regex:/(01)[0-9]{9}/|unique:employees,phone,'.$f_employee->id,
            'gender' => 'required',
            'dob' => 'required|date',
            'present_addr' => 'required',
            'permanent_addr' => 'required',
            'department' => 'required',
            'designation' => 'required',
            'join_date' => 'required',
            'provident_fund' => 'required',
            'salary' => 'required',
            'tada' => 'required',
            'photo' => 'sometimes|image'
        ]);

        if ($validator->fails()) {
            $request->session()->flash('err', 'Please check the highlighted inputs!');
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public');
            $photo = substr($photo, 7);
        } else{
            $photo = $f_employee->photo;
        }


        $employee = $f_employee->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'dob' => date('Y-m-d', strtotime($request->dob)),
            'present_addr' => $request->present_addr,
            'permanent_addr' => $request->permanent_addr,
            'department' => $request->department,
            'designation' => $request->designation,
            'join_date' => date('Y-m-d', strtotime($request->join_date)),
            'provident_fund' => $request->provident_fund,
            'salary' => $request->salary,
            'father_name' => $request->father_name,
            'tada' => $request->tada,
            'photo' => $photo ?? null,
            'employee_type' => $request->employee_type,
        ]);

        if ($employee) {
            $request->session()->flash('msg', 'Employee\'s Information edited Successfully!');
            return redirect()->route('employee.index');
        } else{
            return redirect()->back();
        }

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee = Employee::find($employee)->first();
        $employee_attendance = Attendance::where('employee_id',$employee)->get();
        $employee->delete();
        foreach ($employee_attendance as $attendance) {
            $attendance->delete();
        }
        $employee_expense = EmployeeExpense::where('employee_id',$employee)->get();
        $off_day = OffDay::where('employee_id',$employee)->get();
        $tada = Tada::where('employee_id',$employee)->get();
        $cash_flow = CashFlow::where('employee_id',$employee)->get();
        if($employee_expense){
            $employee_expense->each->delete();
        }
        if ($off_day) {
            $off_day->each->delete();
        }

        return "User deleted Successfully!";
    }


    // For Tada
    public function tada()
    {
        $months = array();
        for ($i = 0; $i < 12; $i++) {
            $timestamp = mktime(0, 0, 0, date('n') - $i, 1);
            $months[date('n', $timestamp)] = date('F', $timestamp);
        }
        $data['employees'] = Employee::with('off_day')->get();
        return view('employees.tada',$data)->with('months',$months);
    }
    public function tada_post(Request $request)
    {
        Session::put('request',$request->all());

resources/views/employees/add.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('err'))
        <div class="alert alert-danger alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i>Error Alert!</h4>
            {{ session('err') }}
        </div>
@endif
<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Add new Employee</h3>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ route('employee.store') }}">
				@csrf
				<div class="box-body">
					<div class="form-group col-sm-3 {{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name">Name</label>
						<input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Enter Name">
						@if ($errors->has('name'))
						<span class="help-block">
							<strong>{{ $errors->first('name') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('email') ? ' has-error' : '' }}">
						<label for="exampleInputEmail1">Email address</label>
						<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') }}">
						@if ($errors->has('email'))
						<span class="help-block">
							<strong>{{ $errors->first('email') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('phone') ? ' has-error' : '' }}">
						<label for="phone">Phone Number</label>
						<input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" value="{{ old('phone') }}">
						@if ($errors->has('phone'))
						<span class="help-block">
							<strong>{{ $errors->first('phone') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('gender') ? ' has-error' : '' }}">
						<label>Gender: </label><br>
						<label>
							<input type="radio" value="m" name="gender" {{ old('gender') == 'm' ? 'checked': '' }}> Male
						</label>
						<label>
							<input type="radio" value="f" name="gender" {{ old('gender') == 'f' ? 'checked': '' }}> Female
						</label>
						@if ($errors->has('gender'))
						<span class="help-block">
							<strong>{{ $errors->first('gender') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('dob') ? ' has-error' : '' }} clearfix">
						<label class="control-label">Date of Birth</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="dob" class="form-control input-sm datepicker" value="{{old('dob')}}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('dob'))
						<span class="help-block">
							<strong>{{ $errors->first('dob') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('present_addr') ? ' has-error' : '' }}">
                        <label>Present Address</label>
                        <textarea name="present_addr" class="form-control input-sm" rows="3">
                        	{{ trim(old('present_addr')) }}
                        </textarea> 
                        @if ($errors->has('present_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('present_addr') }}</strong>
						</span>
						@endif
                    </div>

                    <div class="form-group col-sm-3 {{ $errors->has('permanent_addr') ? ' has-error' : '' }}">
                        <label>Permanent Address</label>
                        <textarea name="permanent_addr" class="form-control input-sm" rows="3">
                        	{{ trim(old('permanent_addr')) }}
                        </textarea>
                        @if ($errors->has('permanent_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('permanent_addr') }}</strong>
						</span>
						@endif
                    </div>
					
					
					<div class="form-group col-sm-3 ">
						<label>Father Name</label>
						<input type="text" class="form-control" name="father_name" placeholder="Father Name" value="{{ old('father_name') }}">
					</div>


					<!--<div class="form-group col-sm-3 {{ $errors->has('department') ? ' has-error' : '' }} clearfix">-->
					<!--	<label for="Department">Department</label>-->
					<!--	<select name="department" class="form-control">-->
					<!--		<option value="">Select</option>-->
					<!--		<option value="Sales" {{ old('department') == 'Sales' ? 'selected': '' }}>Sales</option>-->
					<!--		<option value="IT" {{ old('department') == 'IT' ? 'selected': '' }}>IT</option>-->
					<!--		<option value="Stock" {{ old('department') == 'Stock' ? 'selected': '' }}>Stock</option>-->
					<!--		<option value="Accounts" {{ old('department') == 'Accounts' ? 'selected': '' }}>Accounts</option>-->
					<!--	</select>-->
					<!--	@if ($errors->has('department'))-->
					<!--	<span class="help-block">-->
					<!--		<strong>{{ $errors->first('department') }}</strong>-->
					<!--	</span>-->
					<!--	@endif-->
					<!--</div>-->

					<div class="form-group col-sm-3 clearfix {{ $errors->has('designation') ? ' has-error' : '' }}">
						<label for="designation">Designation</label>
						<select name="designation" class="form-control">
							<option value="">Select</option>
							@foreach($designations as $designation)
								<option value="{{ $designation->id }}">{{ $designation->name }}</option>
							@endforeach
						</select>
						@if ($errors->has('designation'))
						<span class="help-block">
							<strong>{{ $errors->first('designation') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('provident_fund') ? ' has-error' : '' }}">
						<label for="provident_fund">Provident Fund</label>
						<input type="text" name="provident_fund" class="form-control" placeholder="Enter Provident Fund" value="{{ old('provident_fund') }}">
						@if ($errors->has('provident_fund'))
						<span class="help-block">
							<strong>{{ $errors->first('provident_fund') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('tada') ? ' has-error' : '' }}">
						<label for="tada">Ta-Da</label>
						<input type="text" name="tada" class="form-control" placeholder="Enter Tada" value="{{ old('tada') }}">
						@if ($errors->has('tada'))
						<span class="help-block">
							<strong>{{ $errors->first('tada') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('salary') ? ' has-error' : '' }}">
						<label for="salary">Salary</label>
						<input type="text" name="salary" class="form-control" placeholder="Enter salary" value="{{ old('salary') }}">
						@if ($errors->has('salary'))
						<span class="help-block">
							<strong>{{ $errors->first('salary') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('join_date') ? ' has-error' : '' }}">
						<label class="control-label">Joining Date</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="join_date" class="form-control input-sm datepicker" value="{{old('join_date')}}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('join_date'))
						<span class="help-block">
							<strong>{{ $errors->first('join_date') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('photo') ? ' has-error' : '' }}">
						<label for="exampleInputFile">Profile Photo</label>
						<input type="file" id="exampleInputFile" name="photo">
						@if ($errors->has('photo'))
						<span class="help-block">
							<strong>{{ $errors->first('photo') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('employee_type') ? ' has-error' : '' }}">
						<label for="employee_type">Employee type</label>
						<select name="employee_type" class="form-control">
							<option value="">Select</option>
							<option value="1" {{ old('employee_type') == '1' ? 'selected': '' }}>Office Staff</option>
							<option value="2" {{ old('employee_type') == '2' ? 'selected': '' }}>Field Staff</option>
						</select>
						@if ($errors->has('employee_type'))
						<span class="help-block">
							<strong>{{ $errors->first('employee_type') }}</strong>
						</span>
						@endif
					</div>

					
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<button type="submit" class="btn btn-primary btn-lg">Submit</button>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/employees/attendance-single.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <i class="icon fa fa-check"></i>{{ session('msg') }}
            
        </div>
@endif
<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Update Attendance list {{ $date }}</h3>
			</div>
			<updateattendance :date="{{ json_encode($date) }}" :em="{{ json_encode($employees) }}"></updateattendance>

		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/employees/employee-expense.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Employees Expense</h3>
        {{-- <a href="" class="text-right btn btn-success"><i class="fa fa-users fa-fw"></i> Add Employee</a> --}}
    </div>

<employee-expense></employee-expense>

@endsection

resources/views/employees/employee-list.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Employees</h3>
        <a href="{{ route('employee.create') }}" class="text-right btn btn-success"><i class="fa fa-users fa-fw"></i> Add Employee</a>
        <a href="{{ url('employee-export') }}" class="btn btn-success pull-right" style="margin-right: 15px">Download to Excel</a>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example1_info">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Department</th>
                            <th>Designation</th>
                            <th>Joining Date</th>
                            <th>TADA</th>
                            <th>Provident Fund</th>
                            <th>Current Salary</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                            
                    <tbody>
                        @foreach($employees as $employee)
                        <tr>
                            <td>{{ $employee->id }}</td>
                            <td>{{ $employee->name }}</td>
                            <td>{{ $employee->email }}</td>
                            <td>{{ $employee->phone }}</td>
                            <td>{{ $employee->department }}</td>
                            <td>{{ $employee->designation_name->name }}</td>
                            <td>{{ $employee->join_date }}</td>
                            <td>{{ $employee->tada }}</td>
                            <td>{{ $employee->provident_fund }}</td>
                            <td>{{ $employee->salary }}</td>
                            <td>
                                <a href="{{ route('employee.show', ['employee' => $employee->id ]) }}" class="btn btn-info">
                                    <i class="fa fa-user"></i> 
                                </a>
                                <a href="{{ route('employee.edit',['employee' => $employee->id]) }}" class="btn btn-warning">
                                    <i class="fa fa-edit"></i> 
                                </a>
                                
                                <a href="javascript;" class="btn btn-danger" @click.prevent="deleteEmployee({{ $employee->id }})">
                                    <i class="fa fa-trash"></i> 
                                </a>
                            </td>
                            
                        </tr>
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
</div>
@endsection

resources/views/employees/take-attendance.blade.php
@extends('layouts.master')
@section('style')
<style type="text/css">

</style>
@endsection
@section('page_main_content')
<div class="box">
    <div class="box-header">
        <h1 class="box-title">Take Attendance of today <strong> ({{ date("F j, Y") }})</strong></h1>
        <a href="{{ route('attendance.index') }}" class="text-right btn btn-info pull-right"><i class="fa fa-book fa-fw"></i> View Attendance List</a>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<attendance :em="{{ json_encode($employees) }}"></attendance>
</div>
@endsection